### ISSUE TITLE
Mac OS 10.13.5替换后无法启动

### ISSUE THREAD

**Issue by daniel-lu** [datochan/DTEdrawMax#1]
Mac OS 10.13.5替换后，程序无法启动，直接crash。
试过9.0中文版及9.2中文/英文版，均无法成功。
顺序：
1. 运行原版
2. 运行Keygen
3. 生成Key及Activite Code
4. 断网
5. 填入注册信息，点击激活
6. 激活失败，使用手动激活，并填入激活码
7. 替换文件，确认soft link
8. 启动程序，提示崩溃信息

想确认一下，破解补丁是否依赖于QT运行环境？

**Comment by datochan** [comment]
Hi,
补丁文件是依赖QT环境的，应该说由于本软件是QT开发的，我为了不自己拼凑QT对象的内存结构，才用的QT写的补丁文件。补丁所需要的QT链接库，此软件默认都已经集成好了不需要额外集成。

这个补丁是依赖 EdrawMax9.1版本写的，在ReadMe中有写:

> 通过分析可知libObjectModule.dylib文件加载后会在dllmain将公钥赋值给到导出符号: __ZN12LocalizeUtil10s_locCodesE中，Mach0View查看导出符号的偏移是: 0x0535be0。

补丁中直接使用了这个便宜的硬编码，要想提高通用性需要解析 libObjectModule.dylib文件的mach-o文件头动态获取此偏移地址。

你崩溃的原因就是这个偏移地址发生了变化，9.2版本的偏移地址是: `0x052BC70`。
只需要修改补丁文件，重新编译即可。

**Comment by daniel-lu** [comment]
非常感谢你的回复。:)
