### ISSUE TITLE
linux 平台动态库

### ISSUE THREAD

**Issue by SourceLink** [datochan/DTEdrawMax#5]
Hello  一直搞不明天 在linux平台下如何可以修改动态库中指定地址变量的值
您这有什么好的方案吗?

**Comment by datochan** [comment]
我没linux环境，也没研究过linux平台的内容。我想linux应该也有支持elf可执行文件格式的编辑器。
或者你直接用IDA反编译或者调试跟踪一下看，是在导出符号表的哪一个，对应的修改一下，应该是可行的。

linux下加密方式应该是一致的，只是提取哪些硬件信息可能也需要你跟踪一下。
祝你成功！

**Comment by SourceLink** [comment]
明白, 导出符号表已经找到, 但是不知道如何修改这个动态库

 1095: 000000000071cc20    48 OBJECT  GLOBAL DEFAULT   26 _ZN12LocalizeUtil10s_locC

是我的方向搞错了吗?

**Comment by datochan** [comment]
你的方向没错，就是我也没研究过linux，有点儿爱莫能助的感觉，哈哈~

如果能找到linux下的可执行文件编辑器，直接编辑保存就可以了。
如果找不到，就研究一下elf文件格式吧，可以将这个偏移地址计算成文件地址，然后找个hex编辑器，直接像编辑文本一样，编辑保存就行~

**Comment by SourceLink** [comment]
好的, 感谢您的帮助

**Comment by datochan** [comment]
不客气~
